import { createClient } from "@/lib/supabase/server"
import { NextResponse } from "next/server"

export async function POST() {
  try {
    const supabase = await createClient()

    console.log("[v0] Starting medicine setup...")

    const sampleMedicines = [
      {
        name: "Napa",
        generic_name: "Paracetamol",
        company: "Beximco Pharmaceuticals",
        strength: "500mg",
        dosage_form: "Tablet",
        price: 0.8,
        description: "Pain relief and fever reducer",
        category: "pain-relief",
        prescription_required: false,
        stock_quantity: 1000,
      },
      {
        name: "Ace",
        generic_name: "Paracetamol",
        company: "Square Pharmaceuticals",
        strength: "500mg",
        dosage_form: "Tablet",
        price: 0.85,
        description: "Effective pain and fever management",
        category: "pain-relief",
        prescription_required: false,
        stock_quantity: 1000,
      },
      {
        name: "Monas 20",
        generic_name: "Montelukast",
        company: "Incepta Pharmaceuticals",
        strength: "20mg",
        dosage_form: "Tablet",
        price: 8.0,
        description: "For asthma and allergies",
        category: "respiratory",
        prescription_required: true,
        stock_quantity: 500,
      },
      {
        name: "Seclo 20",
        generic_name: "Omeprazole",
        company: "Square Pharmaceuticals",
        strength: "20mg",
        dosage_form: "Capsule",
        price: 3.5,
        description: "Gastric acid reducer",
        category: "gastric",
        prescription_required: false,
        stock_quantity: 800,
      },
      {
        name: "Fexo 120",
        generic_name: "Fexofenadine",
        company: "Square Pharmaceuticals",
        strength: "120mg",
        dosage_form: "Tablet",
        price: 6.0,
        description: "Antihistamine for allergies",
        category: "allergy",
        prescription_required: false,
        stock_quantity: 600,
      },
      {
        name: "Amoxi 500",
        generic_name: "Amoxicillin",
        company: "Beximco Pharmaceuticals",
        strength: "500mg",
        dosage_form: "Capsule",
        price: 4.5,
        description: "Broad spectrum antibiotic",
        category: "antibiotic",
        prescription_required: true,
        stock_quantity: 700,
      },
      {
        name: "Flexi",
        generic_name: "Aceclofenac",
        company: "Incepta Pharmaceuticals",
        strength: "100mg",
        dosage_form: "Tablet",
        price: 5.0,
        description: "Anti-inflammatory pain relief",
        category: "pain-relief",
        prescription_required: false,
        stock_quantity: 500,
      },
      {
        name: "Maxpro 20",
        generic_name: "Esomeprazole",
        company: "Renata Limited",
        strength: "20mg",
        dosage_form: "Tablet",
        price: 4.0,
        description: "Advanced gastric protection",
        category: "gastric",
        prescription_required: false,
        stock_quantity: 600,
      },
      {
        name: "Sergel",
        generic_name: "Sertraline",
        company: "Square Pharmaceuticals",
        strength: "50mg",
        dosage_form: "Tablet",
        price: 8.5,
        description: "Antidepressant medication",
        category: "mental-health",
        prescription_required: true,
        stock_quantity: 300,
      },
      {
        name: "Losectil 20",
        generic_name: "Omeprazole",
        company: "Incepta Pharmaceuticals",
        strength: "20mg",
        dosage_form: "Capsule",
        price: 3.0,
        description: "Gastric ulcer treatment",
        category: "gastric",
        prescription_required: false,
        stock_quantity: 700,
      },
      {
        name: "Ciprocin 500",
        generic_name: "Ciprofloxacin",
        company: "Square Pharmaceuticals",
        strength: "500mg",
        dosage_form: "Tablet",
        price: 7.0,
        description: "Powerful antibiotic",
        category: "antibiotic",
        prescription_required: true,
        stock_quantity: 400,
      },
      {
        name: "Alatrol 10",
        generic_name: "Cetirizine",
        company: "Renata Limited",
        strength: "10mg",
        dosage_form: "Tablet",
        price: 2.5,
        description: "Allergy relief medication",
        category: "allergy",
        prescription_required: false,
        stock_quantity: 900,
      },
      {
        name: "Metformin 500",
        generic_name: "Metformin",
        company: "Square Pharmaceuticals",
        strength: "500mg",
        dosage_form: "Tablet",
        price: 2.0,
        description: "Diabetes management",
        category: "diabetes",
        prescription_required: true,
        stock_quantity: 1000,
      },
      {
        name: "Amlodipine 5",
        generic_name: "Amlodipine",
        company: "Beximco Pharmaceuticals",
        strength: "5mg",
        dosage_form: "Tablet",
        price: 3.0,
        description: "Blood pressure control",
        category: "blood-pressure",
        prescription_required: true,
        stock_quantity: 800,
      },
      {
        name: "Vitamin C 500",
        generic_name: "Ascorbic Acid",
        company: "Square Pharmaceuticals",
        strength: "500mg",
        dosage_form: "Tablet",
        price: 1.5,
        description: "Immune system support",
        category: "vitamin",
        prescription_required: false,
        stock_quantity: 1500,
      },
      {
        name: "Calcium D",
        generic_name: "Calcium + Vitamin D3",
        company: "Renata Limited",
        strength: "500mg+200IU",
        dosage_form: "Tablet",
        price: 4.0,
        description: "Bone health supplement",
        category: "vitamin",
        prescription_required: false,
        stock_quantity: 1000,
      },
      {
        name: "Azithromycin 500",
        generic_name: "Azithromycin",
        company: "Incepta Pharmaceuticals",
        strength: "500mg",
        dosage_form: "Tablet",
        price: 15.0,
        description: "Antibiotic for infections",
        category: "antibiotic",
        prescription_required: true,
        stock_quantity: 300,
      },
      {
        name: "Salbutamol Inhaler",
        generic_name: "Salbutamol",
        company: "Square Pharmaceuticals",
        strength: "100mcg",
        dosage_form: "Inhaler",
        price: 120.0,
        description: "Asthma relief inhaler",
        category: "respiratory",
        prescription_required: true,
        stock_quantity: 200,
      },
      {
        name: "Ranitidine 150",
        generic_name: "Ranitidine",
        company: "Beximco Pharmaceuticals",
        strength: "150mg",
        dosage_form: "Tablet",
        price: 2.0,
        description: "Acid reflux treatment",
        category: "gastric",
        prescription_required: false,
        stock_quantity: 800,
      },
      {
        name: "Loratadine 10",
        generic_name: "Loratadine",
        company: "Renata Limited",
        strength: "10mg",
        dosage_form: "Tablet",
        price: 3.0,
        description: "Non-drowsy allergy relief",
        category: "allergy",
        prescription_required: false,
        stock_quantity: 700,
      },
    ]

    const { data, error } = await supabase.from("medicines").insert(sampleMedicines)

    if (error) {
      console.error("[v0] Insert error:", error)

      return NextResponse.json(
        {
          success: false,
          error: error.message,
          message: "Please create the medicines table in Supabase dashboard first",
        },
        { status: 400 },
      )
    }

    console.log("[v0] Medicines inserted successfully")

    return NextResponse.json({
      success: true,
      message: `Successfully added ${sampleMedicines.length} medicines!`,
      count: sampleMedicines.length,
    })
  } catch (error: any) {
    console.error("[v0] Setup exception:", error)
    return NextResponse.json(
      {
        success: false,
        error: error.message || "Unknown error",
      },
      { status: 500 },
    )
  }
}
