// DIMS (Drug Information Management System) Style Medicine Database
// Complete medicine data with generic names, dosages, and prices

export interface Product {
  id: string
  name: string
  genericName: string // Added generic name for DIMS
  description: string
  price: number
  image: string
  category: string
  prescription?: boolean
  inStock?: boolean
  dosage?: string // Added dosage
  manufacturer?: string // Added manufacturer
  packSize?: string // Added pack size
  strength?: string // Added strength
}

export interface CartItem extends Product {
  quantity: number
}

export const products: Product[] = [
  // Pain & Fever
  {
    id: "napa-500",
    name: "Napa",
    genericName: "Paracetamol",
    description: "জ্বর ও হালকা থেকে মাঝারি ব্যথা উপশমে কার্যকর। মাথাব্যথা, দাঁতের ব্যথা, পেশীর ব্যথায় ব্যবহৃত হয়।",
    price: 0.8,
    image: "/paracetamol-tablet-strip.jpg",
    category: "ব্যথা ও জ্বর",
    prescription: false,
    inStock: true,
    dosage: "প্রতি ৪-৬ ঘন্টায় ১-২ টি ট্যাবলেট",
    manufacturer: "Beximco Pharmaceuticals",
    packSize: "১০ টি/স্ট্রিপ",
    strength: "500mg",
  },
  {
    id: "napa-extend",
    name: "Napa Extend",
    genericName: "Paracetamol",
    description: "দীর্ঘমেয়াদী ব্যথা উপশমের জন্য এক্সটেন্ডেড রিলিজ ফর্মুলা। রাতের ব্যথায় কার্যকর।",
    price: 2.5,
    image: "/paracetamol-extended-release-tablet.jpg",
    category: "ব্যথা ও জ্বর",
    prescription: false,
    inStock: true,
    dosage: "প্রতি ৮ ঘন্টায় ১ টি ট্যাবলেট",
    manufacturer: "Beximco Pharmaceuticals",
    packSize: "১০ টি/স্ট্রিপ",
    strength: "665mg",
  },
  {
    id: "ace-500",
    name: "Ace",
    genericName: "Paracetamol",
    description: "জ্বর ও ব্যথা কমাতে সাহায্য করে। শিশু এবং প্রাপ্তবয়স্ক উভয়ের জন্য নিরাপদ।",
    price: 0.75,
    image: "/ace-paracetamol-tablet.jpg",
    category: "ব্যথা ও জ্বর",
    prescription: false,
    inStock: true,
    dosage: "প্রতি ৪-৬ ঘন্টায় ১-২ টি",
    manufacturer: "Square Pharmaceuticals",
    packSize: "১০ টি/স্ট্রিপ",
    strength: "500mg",
  },

  // Antibiotics
  {
    id: "azithromycin-500",
    name: "Azith",
    genericName: "Azithromycin",
    description: "ব্রড-স্পেকট্রাম অ্যান্টিবায়োটিক। শ্বাসতন্ত্র, ত্বক এবং কানের সংক্রমণে কার্যকর।",
    price: 35.0,
    image: "/azithromycin-antibiotic-tablet.jpg",
    category: "অ্যান্টিবায়োটিক",
    prescription: true,
    inStock: true,
    dosage: "দিনে ১ বার, ৩-৫ দিন",
    manufacturer: "Square Pharmaceuticals",
    packSize: "৩ টি/স্ট্রিপ",
    strength: "500mg",
  },
  {
    id: "ciprofloxacin-500",
    name: "Ciprocin",
    genericName: "Ciprofloxacin",
    description: "ইউরিনারি ট্র্যাক্ট ইনফেকশন, পেটের সংক্রমণ এবং হাড়ের সংক্রমণে ব্যবহৃত।",
    price: 8.0,
    image: "/ciprofloxacin-antibiotic-tablet.jpg",
    category: "অ্যান্টিবায়োটিক",
    prescription: true,
    inStock: true,
    dosage: "দিনে ২ বার, ৭-১৪ দিন",
    manufacturer: "Square Pharmaceuticals",
    packSize: "১০ টি/স্ট্রিপ",
    strength: "500mg",
  },
  {
    id: "amoxicillin-500",
    name: "Moxacil",
    genericName: "Amoxicillin",
    description: "পেনিসিলিন গ্রুপের অ্যান্টিবায়োটিক। কান, নাক, গলা এবং ত্বকের সংক্রমণে কার্যকর।",
    price: 4.5,
    image: "/amoxicillin-capsule-antibiotic.jpg",
    category: "অ্যান্টিবায়োটিক",
    prescription: true,
    inStock: true,
    dosage: "দিনে ৩ বার, ৭ দিন",
    manufacturer: "Square Pharmaceuticals",
    packSize: "১০ টি/স্ট্রিপ",
    strength: "500mg",
  },
  {
    id: "cefixime-200",
    name: "Cef-3",
    genericName: "Cefixime",
    description: "থার্ড জেনারেশন সেফালোস্পোরিন। টনসিলাইটিস, ফ্যারিঞ্জাইটিস এবং ইউটিআই-তে কার্যকর।",
    price: 25.0,
    image: "/cefixime-antibiotic-capsule.jpg",
    category: "অ্যান্টিবায়োটিক",
    prescription: true,
    inStock: true,
    dosage: "দিনে ১-২ বার",
    manufacturer: "Healthcare Pharmaceuticals",
    packSize: "১০ টি/স্ট্রিপ",
    strength: "200mg",
  },

  // Gastric
  {
    id: "omeprazole-20",
    name: "Seclo",
    genericName: "Omeprazole",
    description: "প্রোটন পাম্প ইনহিবিটর। গ্যাস্ট্রিক আলসার, অ্যাসিডিটি এবং জিইআরডি চিকিৎসায় ব্যবহৃত।",
    price: 6.0,
    image: "/omeprazole-gastric-capsule.jpg",
    category: "গ্যাস্ট্রিক",
    prescription: false,
    inStock: true,
    dosage: "দিনে ১ বার, সকালে খালি পেটে",
    manufacturer: "Square Pharmaceuticals",
    packSize: "১৪ টি/স্ট্রিপ",
    strength: "20mg",
  },
  {
    id: "esomeprazole-20",
    name: "Nexium",
    genericName: "Esomeprazole",
    description: "উন্নত পিপিআই। গুরুতর অ্যাসিড রিফ্লাক্স এবং ইরোসিভ এসোফ্যাগাইটিসে কার্যকর।",
    price: 12.0,
    image: "/esomeprazole-tablet-gastric.jpg",
    category: "গ্যাস্ট্রিক",
    prescription: true,
    inStock: true,
    dosage: "দিনে ১ বার",
    manufacturer: "AstraZeneca",
    packSize: "১৪ টি/স্ট্রিপ",
    strength: "20mg",
  },
  {
    id: "ranitidine-150",
    name: "Neoceptin R",
    genericName: "Ranitidine",
    description: "H2 রিসেপ্টর ব্লকার। পেটের অ্যাসিড কমায়। হার্টবার্ন এবং ইন্ডাইজেশনে ব্যবহৃত।",
    price: 2.5,
    image: "/ranitidine-tablet-gastric.jpg",
    category: "গ্যাস্ট্রিক",
    prescription: false,
    inStock: true,
    dosage: "দিনে ২ বার",
    manufacturer: "Square Pharmaceuticals",
    packSize: "১০ টি/স্ট্রিপ",
    strength: "150mg",
  },

  // Diabetes
  {
    id: "metformin-500",
    name: "Comet",
    genericName: "Metformin",
    description: "টাইপ ২ ডায়াবেটিসের প্রথম সারির ওষুধ। রক্তে শর্করার মাত্রা নিয়ন্ত্রণ করে।",
    price: 3.0,
    image: "/metformin-diabetes-tablet.jpg",
    category: "ডায়াবেটিস",
    prescription: true,
    inStock: true,
    dosage: "দিনে ২-৩ বার, খাবারের সাথে",
    manufacturer: "Square Pharmaceuticals",
    packSize: "১০ টি/স্ট্রিপ",
    strength: "500mg",
  },
  {
    id: "glimepiride-2",
    name: "Amaryl",
    genericName: "Glimepiride",
    description: "সালফোনাইলইউরিয়া শ্রেণীর ডায়াবেটিস ওষুধ। ইনসুলিন নিঃসরণ বাড়ায়।",
    price: 8.0,
    image: "/glimepiride-diabetes-tablet.jpg",
    category: "ডায়াবেটিস",
    prescription: true,
    inStock: true,
    dosage: "দিনে ১ বার, সকালে",
    manufacturer: "Sanofi",
    packSize: "১০ টি/স্ট্রিপ",
    strength: "2mg",
  },

  // Blood Pressure
  {
    id: "amlodipine-5",
    name: "Amdocal",
    genericName: "Amlodipine",
    description: "ক্যালসিয়াম চ্যানেল ব্লকার। উচ্চ রক্তচাপ এবং এনজাইনা পেক্টোরিসে ব্যবহৃত।",
    price: 3.5,
    image: "/amlodipine-blood-pressure-tablet.jpg",
    category: "হৃদরোগ",
    prescription: true,
    inStock: true,
    dosage: "দিনে ১ বার",
    manufacturer: "Square Pharmaceuticals",
    packSize: "১০ টি/স্ট্রিপ",
    strength: "5mg",
  },
  {
    id: "losartan-50",
    name: "Losar",
    genericName: "Losartan",
    description: "এআরবি শ্রেণীর ওষুধ। উচ্চ রক্তচাপ এবং ডায়াবেটিক কিডনি রোগে কার্যকর।",
    price: 6.0,
    image: "/losartan-blood-pressure-tablet.jpg",
    category: "হৃদরোগ",
    prescription: true,
    inStock: true,
    dosage: "দিনে ১ বার",
    manufacturer: "Square Pharmaceuticals",
    packSize: "১০ টি/স্ট্রিপ",
    strength: "50mg",
  },
  {
    id: "atenolol-50",
    name: "Tenolol",
    genericName: "Atenolol",
    description: "বিটা ব্লকার। উচ্চ রক্তচাপ, এনজাইনা এবং অনিয়মিত হৃদস্পন্দনে ব্যবহৃত।",
    price: 2.0,
    image: "/atenolol-heart-tablet.jpg",
    category: "হৃদরোগ",
    prescription: true,
    inStock: true,
    dosage: "দিনে ১-২ বার",
    manufacturer: "Square Pharmaceuticals",
    packSize: "১০ টি/স্ট্রিপ",
    strength: "50mg",
  },

  // Allergy
  {
    id: "cetirizine-10",
    name: "Alatrol",
    genericName: "Cetirizine",
    description: "অ্যান্টিহিস্টামিন। অ্যালার্জিক রাইনাইটিস, চুলকানি এবং আমবাতে কার্যকর।",
    price: 3.0,
    image: "/placeholder.svg?height=200&width=200",
    category: "এলার্জি",
    prescription: false,
    inStock: true,
    dosage: "দিনে ১ বার, রাতে",
    manufacturer: "Square Pharmaceuticals",
    packSize: "১০ টি/স্ট্রিপ",
    strength: "10mg",
  },
  {
    id: "fexofenadine-120",
    name: "Fexo",
    genericName: "Fexofenadine",
    description: "নন-সিডেটিভ অ্যান্টিহিস্টামিন। সিজনাল অ্যালার্জি এবং ক্রনিক আর্টিকারিয়ায় ব্যবহৃত।",
    price: 8.0,
    image: "/placeholder.svg?height=200&width=200",
    category: "এলার্জি",
    prescription: false,
    inStock: true,
    dosage: "দিনে ১ বার",
    manufacturer: "Square Pharmaceuticals",
    packSize: "১০ টি/স্ট্রিপ",
    strength: "120mg",
  },
  {
    id: "montelukast-10",
    name: "Montair",
    genericName: "Montelukast",
    description: "লিউকোট্রিন রিসেপ্টর অ্যান্টাগনিস্ট। অ্যাজমা প্রিভেনশন এবং অ্যালার্জিক রাইনাইটিসে ব্যবহৃত।",
    price: 12.0,
    image: "/placeholder.svg?height=200&width=200",
    category: "এলার্জি",
    prescription: true,
    inStock: true,
    dosage: "দিনে ১ বার, রাতে",
    manufacturer: "Cipla",
    packSize: "১০ টি/স্ট্রিপ",
    strength: "10mg",
  },

  // Vitamins
  {
    id: "vitamin-d3-2000",
    name: "D-Rise",
    genericName: "Cholecalciferol (Vitamin D3)",
    description: "ভিটামিন ডি সাপ্লিমেন্ট। হাড়ের স্বাস্থ্য, রোগ প্রতিরোধ ক্ষমতা এবং পেশীর শক্তি বাড়ায়।",
    price: 6.0,
    image: "/placeholder.svg?height=200&width=200",
    category: "ভিটামিন",
    prescription: false,
    inStock: true,
    dosage: "সপ্তাহে ১ বার অথবা চিকিৎসকের পরামর্শ অনুযায়ী",
    manufacturer: "USV",
    packSize: "৪ টি/স্ট্রিপ",
    strength: "2000 IU",
  },
  {
    id: "calcium-vitamin-d",
    name: "Calbo-D",
    genericName: "Calcium + Vitamin D3",
    description: "ক্যালসিয়াম এবং ভিটামিন ডি কম্বিনেশন। হাড়ের ক্ষয় রোধ এবং অস্টিওপোরোসিস প্রতিরোধে সাহায্য করে।",
    price: 8.0,
    image: "/placeholder.svg?height=200&width=200",
    category: "ভিটামিন",
    prescription: false,
    inStock: true,
    dosage: "দিনে ১-২ বার",
    manufacturer: "Square Pharmaceuticals",
    packSize: "৩০ টি/বোতল",
    strength: "500mg + 200IU",
  },
  {
    id: "multivitamin",
    name: "Nutrivit Gold",
    genericName: "Multivitamin + Minerals",
    description: "সম্পূর্ণ মাল্টিভিটামিন। দৈনিক পুষ্টির চাহিদা পূরণ করে। ক্লান্তি দূর করে এবং শক্তি বাড়ায়।",
    price: 15.0,
    image: "/placeholder.svg?height=200&width=200",
    category: "ভিটামিন",
    prescription: false,
    inStock: true,
    dosage: "দিনে ১ বার, খাবারের পর",
    manufacturer: "Square Pharmaceuticals",
    packSize: "৩০ টি/বোতল",
    strength: "Multi-formula",
  },

  // Medical Devices
  {
    id: "digital-thermometer",
    name: "ডিজিটাল থার্মোমিটার",
    genericName: "Digital Thermometer",
    description: "দ্রুত ও নির্ভুল তাপমাত্রা পরিমাপ। এলসিডি ডিসপ্লে এবং বিপ সাউন্ড সহ।",
    price: 150.0,
    image: "/placeholder.svg?height=200&width=200",
    category: "চিকিৎসা যন্ত্র",
    prescription: false,
    inStock: true,
    manufacturer: "Generic",
    packSize: "১ টি",
  },
  {
    id: "bp-monitor",
    name: "ব্লাড প্রেশার মনিটর",
    genericName: "Digital Blood Pressure Monitor",
    description: "স্বয়ংক্রিয় ডিজিটাল বিপি মেশিন। বড় ডিসপ্লে, মেমোরি ফাংশন এবং অনিয়মিত হার্টবিট ডিটেক্টর।",
    price: 1800.0,
    image: "/placeholder.svg?height=200&width=200",
    category: "চিকিৎসা যন্ত্র",
    prescription: false,
    inStock: true,
    manufacturer: "Omron",
    packSize: "১ টি",
  },
  {
    id: "glucometer",
    name: "গ্লুকোমিটার সেট",
    genericName: "Blood Glucose Monitor",
    description: "ডায়াবেটিস রোগীদের জন্য রক্তে শর্করা পরিমাপক। ২৫টি স্ট্রিপ এবং ল্যান্সেট সহ।",
    price: 1200.0,
    image: "/placeholder.svg?height=200&width=200",
    category: "চিকিৎসা যন্ত্র",
    prescription: false,
    inStock: true,
    manufacturer: "Accu-Chek",
    packSize: "১ সেট",
  },
  {
    id: "pulse-oximeter",
    name: "পালস অক্সিমিটার",
    genericName: "Pulse Oximeter",
    description: "আঙ্গুলে লাগিয়ে অক্সিজেন স্যাচুরেশন এবং পালস রেট পরিমাপ করে। OLED ডিসপ্লে।",
    price: 800.0,
    image: "/placeholder.svg?height=200&width=200",
    category: "চিকিৎসা যন্ত্র",
    prescription: false,
    inStock: true,
    manufacturer: "Generic",
    packSize: "১ টি",
  },

  // PPE & Hygiene
  {
    id: "surgical-mask-50",
    name: "সার্জিক্যাল মাস্ক",
    genericName: "3-Ply Surgical Face Mask",
    description: "৩-প্লাই ডিসপোজেবল মাস্ক। ব্যাকটেরিয়া এবং ধুলোবালি থেকে সুরক্ষা দেয়।",
    price: 200.0,
    image: "/placeholder.svg?height=200&width=200",
    category: "পিপিই",
    prescription: false,
    inStock: true,
    manufacturer: "Generic",
    packSize: "৫০ টি/বক্স",
  },
  {
    id: "hand-sanitizer-500",
    name: "হ্যান্ড স্যানিটাইজার",
    genericName: "Alcohol-based Hand Sanitizer",
    description: "৭০% অ্যালকোহল বেসড। জীবাণুনাশক। পানি ছাড়াই হাত পরিষ্কার করে।",
    price: 150.0,
    image: "/placeholder.svg?height=200&width=200",
    category: "স্বাস্থ্যবিধি",
    prescription: false,
    inStock: true,
    manufacturer: "Generic",
    packSize: "৫০০ মিলি",
  },
]
